from django.urls import path

from . import views

urlpatterns = [
    path("health/", views.health, name="health"),
    path("health", views.health),
    path("merge/", views.MergeView.as_view(), name="merge"),
    path("merge", views.MergeView.as_view()),
    path("split/", views.SplitView.as_view(), name="split"),
    path("split", views.SplitView.as_view()),
    path("compress/", views.CompressView.as_view(), name="compress"),
    path("compress", views.CompressView.as_view()),
    path("rotate/", views.RotateView.as_view(), name="rotate"),
    path("rotate", views.RotateView.as_view()),
    path("pdf-to-jpg/", views.PdfToJpgView.as_view(), name="pdf-to-jpg"),
    path("pdf-to-jpg", views.PdfToJpgView.as_view()),
    path("pdf-to-word/", views.PdfToWordView.as_view(), name="pdf-to-word"),
    path("pdf-to-word", views.PdfToWordView.as_view()),
    path("word-to-pdf/", views.WordToPdfView.as_view(), name="word-to-pdf"),
    path("word-to-pdf", views.WordToPdfView.as_view()),
    path("protect/", views.ProtectView.as_view(), name="protect"),
    path("protect", views.ProtectView.as_view()),
    path("unlock/", views.UnlockView.as_view(), name="unlock"),
    path("unlock", views.UnlockView.as_view()),
    path("repair/", views.RepairView.as_view(), name="repair"),
    path("repair", views.RepairView.as_view()),
    path("ppt-to-pdf/", views.OfficeToPdfView.as_view(), name="ppt-to-pdf"),
    path("ppt-to-pdf", views.OfficeToPdfView.as_view()),
    path("excel-to-pdf/", views.OfficeToPdfView.as_view(), name="excel-to-pdf"),
    path("excel-to-pdf", views.OfficeToPdfView.as_view()),
    path("html-to-pdf/", views.OfficeToPdfView.as_view(), name="html-to-pdf"),
    path("html-to-pdf", views.OfficeToPdfView.as_view()),
    path("pdf-to-markdown/", views.PdfToMarkdownView.as_view(), name="pdf-to-markdown"),
    path("pdf-to-markdown", views.PdfToMarkdownView.as_view()),
    path("pdf-to-ppt/", views.PdfToPptxView.as_view(), name="pdf-to-ppt"),
    path("pdf-to-ppt", views.PdfToPptxView.as_view()),
    path("pdf-to-excel/", views.PdfToXlsxView.as_view(), name="pdf-to-excel"),
    path("pdf-to-excel", views.PdfToXlsxView.as_view()),
    path("ocr/", views.OcrView.as_view(), name="ocr"),
    path("ocr", views.OcrView.as_view()),
    path("pdf-to-pdfa/", views.PdfToPdfaView.as_view(), name="pdf-to-pdfa"),
    path("pdf-to-pdfa", views.PdfToPdfaView.as_view()),
    path("compare/", views.ComparePdfView.as_view(), name="compare"),
    path("compare", views.ComparePdfView.as_view()),
    path("summarize/", views.SummarizeView.as_view(), name="summarize"),
    path("summarize", views.SummarizeView.as_view()),
    path("translate/", views.TranslateView.as_view(), name="translate"),
    path("translate", views.TranslateView.as_view()),
    # Browser-side tools reporting a run. Registered both ways like everything
    # else here, since APPEND_SLASH is off and sendBeacon will not follow a 308.
    path("track/", views.TrackView.as_view(), name="track"),
    path("track", views.TrackView.as_view()),
]
